doc: add sample for pushing non JSON docs
coveo/push-api-client.js pull request #145
Opened 2022-05-12 03:45 UTC by louis-bompart

2022-05-12 13:12 UTC, y-lakhdar requested changes
-  [ ] Manual tests

2022-05-12 15:38 UTC, louis-bompart commented on samples/pushBatchOfNonJSONDocuments.ts
> +    addOrUpdate: myDocuments,
> The delete array is mandatory

Well. It worked without on my machine

2022-05-12 18:48 UTC, y-lakhdar commented on samples/pushBatchOfNonJSONDocuments.ts
> +    addOrUpdate: myDocuments,
without getting typing errors?

2022-05-12 19:51 UTC, louis-bompart commented on samples/pushBatchOfNonJSONDocuments.ts
> +    addOrUpdate: myDocuments,
Oupps nvm, fixed.

2022-05-13 10:17 UTC, y-lakhdar approved these changes

2022-05-13 14:35 UTC, merged